// --- Velvet Roast Product Catalog Database ---
const products = [
  { 
    id: 'cappuccino', 
    name: 'Cappuccino', 
    category: 'Coffee', 
    subtitle: 'Hot Coffee', 
    price: 120, 
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&q=80&w=300',
    description: 'A classic espresso drink made with equal parts double espresso, steamed milk, and velvety foam. Dusted with dark cocoa powder.',
    dietary: ['Veg'],
    nutrition: { kcal: 120, caffeine: 150, sugar: 8 },
    ingredients: ['Espresso', 'Whole Milk', 'Cocoa Powder'],
    stock: 25,
    isPopular: true
  },
  { 
    id: 'latte', 
    name: 'Latte', 
    category: 'Coffee', 
    subtitle: 'Hot Coffee', 
    price: 130, 
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=300',
    description: 'A smooth and creamy blend of fresh espresso, steamed milk, and a thin, delicate layer of microfoam on top.',
    dietary: ['Veg'],
    nutrition: { kcal: 190, caffeine: 150, sugar: 15 },
    ingredients: ['Espresso', 'Steamed Milk', 'Vanilla syrup (optional)'],
    stock: 35,
    isPopular: false
  },
  { 
    id: 'americano', 
    name: 'Americano', 
    category: 'Coffee', 
    subtitle: 'Hot Coffee', 
    price: 110, 
    image: 'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&q=80&w=300',
    description: 'Rich, full-bodied espresso diluted with hot water to create a robust, drip-style coffee with crema.',
    dietary: ['Veg', 'Vegan', 'Dairy-Free'],
    nutrition: { kcal: 15, caffeine: 225, sugar: 0 },
    ingredients: ['Espresso', 'Filtered Hot Water'],
    stock: 50,
    isPopular: false
  },
  { 
    id: 'mocha', 
    name: 'Mocha', 
    category: 'Coffee', 
    subtitle: 'Hot Coffee', 
    price: 140, 
    image: 'https://images.unsplash.com/photo-1596078841242-12e73dc697c4?auto=format&fit=crop&q=80&w=300',
    description: 'Decadent chocolate syrup combined with fresh espresso, steamed milk, and finished with whipped cream.',
    dietary: ['Veg'],
    nutrition: { kcal: 320, caffeine: 150, sugar: 32 },
    ingredients: ['Espresso', 'Steamed Milk', 'Chocolate Ganache', 'Whipped Cream'],
    stock: 18,
    isPopular: true
  },
  { 
    id: 'iced-coffee', 
    name: 'Iced Coffee', 
    category: 'Cold Drinks', 
    subtitle: 'Cold Drink', 
    price: 150, 
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=300',
    description: 'Freshly brewed espresso cooled and served over ice, sweetened with simple syrup and dairy cream.',
    dietary: ['Veg'],
    nutrition: { kcal: 140, caffeine: 150, sugar: 12 },
    ingredients: ['Espresso', 'Ice Cubes', 'Whole Milk', 'Cane Syrup'],
    stock: 22,
    isPopular: true
  },
  { 
    id: 'cold-chocolate', 
    name: 'Cold Chocolate', 
    category: 'Cold Drinks', 
    subtitle: 'Cold Drink', 
    price: 160, 
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=300',
    description: 'Premium chilled milk blended with rich Swiss chocolate powder, cocoa shavings, and a scoop of vanilla ice cream.',
    dietary: ['Veg'],
    nutrition: { kcal: 380, caffeine: 5, sugar: 40 },
    ingredients: ['Chilled Milk', 'Cocoa Powder', 'Vanilla Ice Cream', 'Chocolate Drizzle'],
    stock: 12,
    isPopular: false
  },
  { 
    id: 'lemon-iced-tea', 
    name: 'Lemon Iced Tea', 
    category: 'Cold Drinks', 
    subtitle: 'Cold Drink', 
    price: 120, 
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=300',
    description: 'Refreshing organic black tea brewed with fresh lemon juice, sweetened and served over crushed ice with fresh mint.',
    dietary: ['Veg', 'Vegan', 'Dairy-Free'],
    nutrition: { kcal: 90, caffeine: 40, sugar: 22 },
    ingredients: ['Brewed Black Tea', 'Fresh Lemon Juice', 'Mint Leaves', 'Ice'],
    stock: 30,
    isPopular: true
  },
  { 
    id: 'green-tea', 
    name: 'Green Tea', 
    category: 'Tea', 
    subtitle: 'Hot Tea', 
    price: 100, 
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&q=80&w=300',
    description: 'Steeped organic Sencha green tea leaves offering a grassy, clean flavor profile packed with antioxidants.',
    dietary: ['Veg', 'Vegan', 'Dairy-Free'],
    nutrition: { kcal: 2, caffeine: 35, sugar: 0 },
    ingredients: ['Japanese Sencha Green Tea Leaves', 'Hot Water'],
    stock: 45,
    isPopular: false
  },
  { 
    id: 'chocolate-cake', 
    name: 'Chocolate Cake', 
    category: 'Desserts', 
    subtitle: 'Dessert', 
    price: 180, 
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=300',
    description: 'A decadent slice of triple-layered chocolate fudge cake, filled and frosted with dark chocolate ganache.',
    dietary: ['Veg'],
    nutrition: { kcal: 450, caffeine: 10, sugar: 48 },
    ingredients: ['Wheat Flour', 'Dark Cocoa', 'Butter', 'Sugar', 'Baking Powder'],
    stock: 8,
    isPopular: true
  },
  { 
    id: 'blueberry-muffin', 
    name: 'Blueberry Muffin', 
    category: 'Desserts', 
    subtitle: 'Dessert', 
    price: 120, 
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&q=80&w=300',
    description: 'Moist, golden muffin baked with fresh blueberries and topped with a sweet, crunchy sugar streusel.',
    dietary: ['Veg'],
    nutrition: { kcal: 280, caffeine: 0, sugar: 20 },
    ingredients: ['Fresh Blueberries', 'Wheat Flour', 'Butter', 'Brown Sugar'],
    stock: 14,
    isPopular: false
  },
  { 
    id: 'veg-sandwich', 
    name: 'Veg Sandwich', 
    category: 'Snacks', 
    subtitle: 'Snacks', 
    price: 150, 
    image: 'https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?auto=format&fit=crop&q=80&w=300',
    description: 'Fresh cucumbers, tomatoes, and bell peppers layered with cream cheese and spicy green chutney on sourdough bread.',
    dietary: ['Veg'],
    nutrition: { kcal: 310, caffeine: 0, sugar: 4 },
    ingredients: ['Sourdough Bread', 'Cucumber', 'Tomato', 'Bell Pepper', 'Cream Cheese'],
    stock: 0, // Out of Stock to show empty stock state
    isPopular: true
  },
  { 
    id: 'cheese-burger', 
    name: 'Cheese Burger', 
    category: 'Snacks', 
    subtitle: 'Snacks', 
    price: 160, 
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=300',
    description: 'A grilled potato patty topped with cheddar cheese, crisp lettuce, red onions, gherkins, and house secret sauce.',
    dietary: ['Veg'],
    nutrition: { kcal: 420, caffeine: 0, sugar: 6 },
    ingredients: ['Brioche Bun', 'Potato Patty', 'Cheddar Slice', 'Lettuce', 'Secret Sauce'],
    stock: 16,
    isPopular: false
  }
];
